version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: codemaker
    versions:
    - ">= 0"
  - dependency-name: "@jsii/*"
    versions:
    - ">= 0"
  - dependency-name: jsii*
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - ">=11.0.0-0"
  - dependency-name: "@types/node"
    versions:
    - 10.17.51
    - 10.17.52
    - 10.17.53
    - 10.17.54
    - 10.17.55
    - 10.17.56
    - 10.17.57
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: parcel
    versions:
    - 2.0.0-nightly.554
    - 2.0.0-nightly.558
    - 2.0.0-nightly.560
    - 2.0.0-nightly.562
    - 2.0.0-nightly.566
    - 2.0.0-nightly.570
    - 2.0.0-nightly.573
    - 2.0.0-nightly.574
    - 2.0.0-nightly.577
    - 2.0.0-nightly.579
    - 2.0.0-nightly.585
    - 2.0.0-nightly.590
    - 2.0.0-nightly.592
    - 2.0.0-nightly.596
    - 2.0.0-nightly.597
    - 2.0.0-nightly.598
    - 2.0.0-nightly.600
    - 2.0.0-nightly.603
    - 2.0.0-nightly.605
    - 2.0.0-nightly.606
    - 2.0.0-nightly.607
    - 2.0.0-nightly.608
    - 2.0.0-nightly.609
    - 2.0.0-nightly.610
    - 2.0.0-nightly.614
    - 2.0.0-nightly.615
    - 2.0.0-nightly.618
    - 2.0.0-nightly.619
    - 2.0.0-nightly.620
    - 2.0.0-nightly.623
    - 2.0.0-nightly.625
    - 2.0.0-nightly.626
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
